"""'Migration2'

Revision ID: 328744d2737a
Revises: b0bafec2220a
Create Date: 2020-12-01 11:43:53.753833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328744d2737a'
down_revision = 'b0bafec2220a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('newconferences_conferences_confid_fk', 'NewConferences', type_='foreignkey')
    op.create_foreign_key(None, 'NewConferences', 'Conferences', ['NewCnfID'], ['ConfID'])
    op.drop_constraint('newusers_usersinfo_authenticationid_fk', 'NewUsers', type_='foreignkey')
    op.create_foreign_key(None, 'NewUsers', 'UsersInfo', ['NewUserID'], ['AuthenticationID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'NewUsers', type_='foreignkey')
    op.create_foreign_key('newusers_usersinfo_authenticationid_fk', 'NewUsers', 'UsersInfo', ['NewUserID'], ['AuthenticationID'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'NewConferences', type_='foreignkey')
    op.create_foreign_key('newconferences_conferences_confid_fk', 'NewConferences', 'Conferences', ['NewCnfID'], ['ConfID'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
