"""empty message

Revision ID: 529ba989af26
Revises: 3c67e2a5205d
Create Date: 2020-11-29 16:41:12.157917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '529ba989af26'
down_revision = '3c67e2a5205d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('City', 'CityName',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint('city_country_countrycode_fk', 'City', type_='foreignkey')
    op.create_foreign_key(None, 'City', 'Country', ['CountryCode'], ['CountryCode'])
    op.alter_column('ConferenceRoles', 'Role',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('conferenceroles_conferences_confid_fk', 'ConferenceRoles', type_='foreignkey')
    op.drop_constraint('conferenceroles_usersinfo_authenticationid_fk', 'ConferenceRoles', type_='foreignkey')
    op.create_foreign_key(None, 'ConferenceRoles', 'Conferences', ['ConfID'], ['ConfID'])
    op.create_foreign_key(None, 'ConferenceRoles', 'Users', ['AuthenticationID'], ['AuthenticationID'])
    op.drop_constraint('conferencetags_conferences_confid_fk', 'ConferenceTags', type_='foreignkey')
    op.create_foreign_key(None, 'ConferenceTags', 'Conferences', ['ConfID'], ['ConfID'])
    op.alter_column('Conferences', 'CreationDateTime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Conferences', 'CreatorUser',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Conferences', 'EndDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Conferences', 'Name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Conferences', 'ShortName',
               existing_type=sa.VARCHAR(length=19),
               nullable=True)
    op.alter_column('Conferences', 'StartDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Conferences', 'SubmissionDeadLine',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Conferences', 'Year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'Conferences', 'UsersInfo', ['CreatorUser'], ['AuthenticationID'])
    op.alter_column('Country', 'CountryName',
               existing_type=sa.CHAR(length=50),
               nullable=True)
    op.add_column('Submissions', sa.Column('PrevSubmission', sa.INTEGER(), nullable=True))
    op.drop_constraint('submissions_usersinfo_authenticationid_fk', 'Submissions', type_='foreignkey')
    op.drop_constraint('submissions_conferences_confid_fk', 'Submissions', type_='foreignkey')
    op.create_foreign_key(None, 'Submissions', 'UsersInfo', ['AuthenticationID'], ['AuthenticationID'])
    op.create_foreign_key(None, 'Submissions', 'Conferences', ['ConfID'], ['ConfID'])
    op.alter_column('UserLog', 'Address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('UserLog', 'Affiliation',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('UserLog', 'City',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('UserLog', 'Country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('UserLog', 'LastName',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('UserLog', 'Name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('UserLog', 'Password',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('UserLog', 'Phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('UserLog', 'PrimaryEmail',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('UserLog', 'RecordCreationDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('UserLog', 'Salutation',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('Users', 'Password',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('Users', 'Username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index('users_username_uindex', table_name='Users')
    op.drop_constraint('users_users_info_authenticationid_fk', 'Users', type_='foreignkey')
    op.create_foreign_key(None, 'Users', 'UsersInfo', ['AuthenticationID'], ['AuthenticationID'])
    op.alter_column('UsersInfo', 'Affiliation',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('UsersInfo', 'LastName',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('UsersInfo', 'Name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('UsersInfo', 'Password',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('UsersInfo', 'PrimaryEmail',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('UsersInfo', 'RecordCreationDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('UsersInfo', 'Salutation',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UsersInfo', 'Salutation',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('UsersInfo', 'RecordCreationDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('UsersInfo', 'PrimaryEmail',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('UsersInfo', 'Password',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('UsersInfo', 'Name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('UsersInfo', 'LastName',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('UsersInfo', 'Affiliation',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.create_foreign_key('users_users_info_authenticationid_fk', 'Users', 'UsersInfo', ['AuthenticationID'], ['AuthenticationID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('users_username_uindex', 'Users', ['Username'], unique=True)
    op.alter_column('Users', 'Username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('Users', 'Password',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('UserLog', 'Salutation',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('UserLog', 'RecordCreationDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('UserLog', 'PrimaryEmail',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('UserLog', 'Phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('UserLog', 'Password',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('UserLog', 'Name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('UserLog', 'LastName',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('UserLog', 'Country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('UserLog', 'City',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('UserLog', 'Affiliation',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('UserLog', 'Address',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'Submissions', type_='foreignkey')
    op.drop_constraint(None, 'Submissions', type_='foreignkey')
    op.create_foreign_key('submissions_conferences_confid_fk', 'Submissions', 'Conferences', ['ConfID'], ['ConfID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('submissions_usersinfo_authenticationid_fk', 'Submissions', 'UsersInfo', ['AuthenticationID'], ['AuthenticationID'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('Submissions', 'PrevSubmission')
    op.alter_column('Country', 'CountryName',
               existing_type=sa.CHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'Conferences', type_='foreignkey')
    op.alter_column('Conferences', 'Year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Conferences', 'SubmissionDeadLine',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Conferences', 'StartDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Conferences', 'ShortName',
               existing_type=sa.VARCHAR(length=19),
               nullable=False)
    op.alter_column('Conferences', 'Name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Conferences', 'EndDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Conferences', 'CreatorUser',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Conferences', 'CreationDateTime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'ConferenceTags', type_='foreignkey')
    op.create_foreign_key('conferencetags_conferences_confid_fk', 'ConferenceTags', 'Conferences', ['ConfID'], ['ConfID'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'ConferenceRoles', type_='foreignkey')
    op.drop_constraint(None, 'ConferenceRoles', type_='foreignkey')
    op.create_foreign_key('conferenceroles_usersinfo_authenticationid_fk', 'ConferenceRoles', 'UsersInfo', ['AuthenticationID'], ['AuthenticationID'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('conferenceroles_conferences_confid_fk', 'ConferenceRoles', 'Conferences', ['ConfID'], ['ConfID'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('ConferenceRoles', 'Role',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'City', type_='foreignkey')
    op.create_foreign_key('city_country_countrycode_fk', 'City', 'Country', ['CountryCode'], ['CountryCode'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('City', 'CityName',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
